wallpaper {
  monitor = eDP-1
  path = ~/.wallpaper/LakesideDeer-2.png
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/.wallpaper/PaintingStudio-02.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-1
  path = ~/.wallpaper/Rocknergy-2.png
}

splash = false
ipc = off
