[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "tuigreet --cmd /usr/bin/zsh"
user = "antoine"

[initial_session]
command = "Hyprland"
user = "antoine"

[theme]
border = "magenta"
text = "cyan"
prompt = "green"
time = "red"
action = "blue"
button = "yellow"
container = "black"
input = "red"
