import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

# [colors.primary]
# background = "#1d1f21"
# foreground = "#c5c8c6"

[cursor]
blink_interval = 750
thickness = 0.2
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 0.8
title = "Alacritty"

[window.dimensions]
columns = 90
lines = 32

[window.padding]
x = 10
y = 10
